source "$DOTFILES/zshrc/exports.zsh"
source "$DOTFILES/zshrc/aliases.zsh"
source "$DOTFILES/zshrc/typesets.zsh"
source "$DOTFILES/zshrc/functions.zsh"
source "$DOTFILES/zshrc/sources.zsh"
source "$DOTFILES/zshrc/config.zsh"
