# Taps
tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

# Brews (Formulae / Packages)
brew "readline"
brew "xz"
brew "awscli"
brew "bat"
brew "docker"
brew "docker-compose"
brew "exa"
brew "gdal"
brew "git"
brew "gradle@6"
brew "httpie"
brew "jenv"
brew "nvm"
brew "openjdk"
brew "openssl@3"
brew "postgresql@14", restart_service: true
brew "postgis"
brew "postgresql@13"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "watchman"
brew "yarn"
brew "zlib"
brew "zsh-autosuggestions"

# Casks (Applications)
cask "adoptopenjdk8"
cask "corretto"
cask "google-chrome"
cask "iterm2"
cask "raycast"
cask "visual-studio-code"
cask "dropbox"