export ANDROID_HOME="$HOME/Library/Android/sdk" # https://reactnative.dev/docs/environment-setup
export BREWFILE="$HOME/.dotfiles/Brewfile"
export DOTFILES="$HOME/.dotfiles"
export DYLD_LIBRARY_PATH=/usr/local/lib # C (will not work on Mac https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-dyld-environment-variables)
export GEM_HOME="$HOME/.gem"
export LIBRARY_PATH=/usr/local/lib # C
export LOAD="$HOME/.dotfiles/zshrc/load"
export MANPAGER="sh -c 'col -bx | bat -l man -p'" # Syntax highlighting for man pages using bat
export NGROK_DOMAIN="174ee0e60828-8717937222566027958.ngrok-free.app"
export NGROK_EDGE="edghts_2V6yxVlqRRVcUEyJUQONjCkPWo1"
export NULLCMD=bat          # Use bat instead of cat
export NVM_DIR="$HOME/.nvm" # https://github.com/nvm-sh/nvm#installing-and-updating
export PNPM_HOME="$HOME/Library/pnpm"
export PYENV_ROOT="$HOME/.pyenv" # https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
export RBENV_SHELL=zsh           # rbenv
export WORK="$HOME/work/main.code-workspace"
export ZSHRC="$HOME/.zshrc"
