export ANDROID_HOME="$HOME/Library/Android/sdk" # https://reactnative.dev/docs/environment-setup
export BREWFILE="$HOME/.dotfiles/Brewfile"
export DOTFILES="$HOME/.dotfiles"
export GEM_HOME="$HOME/.gem"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home # https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/macos-install.html
export LOAD="$HOME/.dotfiles/zshrc/load"
export MANPAGER="sh -c 'col -bx | bat -l man -p'" # Syntax highlighting for man pages using bat
export NULLCMD=bat # Use bat instead of cat
export NVM_DIR="$HOME/.nvm" # https://github.com/nvm-sh/nvm#installing-and-updating
export PNPM_HOME="$HOME/Library/pnpm"
export PYENV_ROOT="$HOME/.pyenv" # https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
export RBENV_SHELL=zsh # rbenv
export WORK="$HOME/Work/main.code-workspace"
export ZSHRC="$HOME/.zshrc"